services:
  # 1. The Main Brain API
  brain:
    build:
      context: ../
      dockerfile: infrastructure/Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ../:/app # Maps your code safely without touching the venv
    env_file:
      - ../shared/.env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/infrastructure/google_creds.json
      - TZ=Asia/Kolkata
    command: uv run uvicorn backend.api:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - weather-mcp
      - news-mcp

  # 2. The Weather Server
  weather-mcp:
    build:
      context: ../
      dockerfile: infrastructure/Dockerfile.mcp
    ports:
      - "8001:8001"
    volumes:
      - ../:/app
    command: uv run python mcp_servers/weather_mcp/weather_server.py

  # 3. The News Server
  news-mcp:
    build:
      context: ../
      dockerfile: infrastructure/Dockerfile.mcp
    ports:
      - "8002:8002"
    volumes:
      - ../:/app
    command: uv run python mcp_servers/news_mcp/news_server.py

  frontend:
    build:
      context: ../
      dockerfile: infrastructure/Dockerfile.frontend
    ports:
      - "8501:8501"
    volumes:
      - ../frontend:/app/frontend
    environment:
      - TZ=Asia/Kolkata
    command: streamlit run frontend/main_ui.py --server.address 0.0.0.0
    depends_on:
      - brain