FROM python:3.12-slim

WORKDIR /app

# Install dependencies
COPY frontend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the frontend code
COPY frontend /app/frontend

# Expose Streamlit's default port
EXPOSE 8501