FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim

# Tell uv to create and look for the venv completely outside the app directory
ENV UV_PROJECT_ENVIRONMENT=/uv_venv

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    g++ \
    && rm -rf /var/lib/apt/lists/*

COPY pyproject.toml uv.lock ./

# uv will now automatically build into /uv_venv
RUN uv sync --no-dev --group backend

COPY . .

EXPOSE 8000